# Generated by Django 4.1.5 on 2023-01-28 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0001_initial'),
        ('Products', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(choices=[('Alimento', 'Alimento'), ('Medicamentos', 'Medicamentos'), ('Ropa y Accesorios', 'Ropa y Accesorios'), ('Juguetes', 'Juguetes')], on_delete=django.db.models.deletion.CASCADE, to='Categories.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=50, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.BooleanField(verbose_name='Stock'),
        ),
    ]
