# Generated by Django 4.1.5 on 2023-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_product_category_alter_product_name_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='animal',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro animal', 'Otro animal')], default=1, max_length=12, verbose_name='Animal'),
            preserve_default=False,
        )
    ]
