# Generated by Django 4.1.4 on 2023-01-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Alimento', 'Alimento'), ('Medicamentos', 'Medicamentos'), ('Ropa y Accesorios', 'Ropa y Accesorios'), ('Juguetes', 'Juguetes')], max_length=50, verbose_name='Categoria'),
        ),
    ]
